name: "Admin: Prod"

on:
  push:
    branches: [prod]
    paths:
      - "deployments/admin/prod/**"
      - "modules/s3-frontend/**"
      - "modules/cloudfront/**"
      - "modules/secrets-manager/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/_terraform-reusable.yml
    with:
      working_directory: deployments/admin/prod
      environment: prod
    secrets:
      AWS_ROLE_ARN: ${{ secrets.PROD_TF_AWS_ROLE_ARN }}
