name: "Admin: Stage"

on:
  push:
    branches: [stage]
    paths:
      - "deployments/admin/stage/**"
      - "modules/s3-frontend/**"
      - "modules/cloudfront/**"
      - "modules/secrets-manager/**"
  pull_request:
    branches: [stage]
    paths:
      - "deployments/admin/stage/**"
      - "modules/**"
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/_terraform-reusable.yml
    with:
      working_directory: deployments/admin/stage
      environment: stage
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.STAGE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGE_AWS_SECRET_ACCESS_KEY }}
