name: "Admin: Prod"

on:
  push:
    branches: [main]
    paths:
      - "deployments/admin/prod/**"
      - "modules/s3-frontend/**"
      - "modules/cloudfront/**"
      - "modules/secrets-manager/**"
  pull_request:
    branches: [main]
    paths:
      - "deployments/admin/prod/**"
      - "modules/**"
  workflow_dispatch:
concurrency:  group: admin-prod  cancel-in-progress: false

jobs:
  terraform:
    uses: ./.github/workflows/_terraform-reusable.yml
    with:
      working_directory: deployments/admin/prod
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
