name: "ECS: Prod"

on:
  push:
    branches: [main]
    paths:
      - "deployments/ecs/prod/**"
      - "modules/vpc/**"
      - "modules/kms/**"
      - "modules/security-groups/**"
      - "modules/ecr/**"
      - "modules/alb/**"
      - "modules/ecs-cluster/**"
      - "modules/ecs-service/**"
      - "modules/codedeploy/**"
      - "modules/cicd/**"
      - "modules/rds/**"
      - "modules/bastion/**"
      - "modules/cloudtrail/**"
  pull_request:
    branches: [main]
    paths:
      - "deployments/ecs/prod/**"
      - "modules/**"
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/_terraform-reusable.yml
    with:
      working_directory: deployments/ecs/prod
      environment: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
