name: "Shared: IAM"

on:
  push:
    branches: [stage]
    paths:
      - "deployments/shared/iam/**"
      - "modules/iam-cicd/**"
  pull_request:
    branches: [stage]
    paths:
      - "deployments/shared/iam/**"
      - "modules/iam-cicd/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/_terraform-reusable.yml
    with:
      working_directory: deployments/shared/iam
      environment: stage
    secrets:
      AWS_ROLE_ARN: ${{ secrets.STAGE_TF_AWS_ROLE_ARN }}
